In [1]:
import pandas as pd
from dividend.get_dividend import *
pd.options.display.max_rows = 9999

In [2]:
get_data_from_pdf(1301, 2022, 'Q3', path_save = 'tests/')

[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
The output file size is 8.84× larger than the input file.
Possible reasons for this include:
--force-ocr was issued, causing transcoding.
Optimization was disabled.

'_'

In [1]:
import pandas as pd

df = pd.read_csv('/Users/mac/Monthy/Crawl_buffett/docs/List_company_23052023 - Listing.csv')

In [4]:
df[::-1].sort_index()

      Symbol check
0       1301  Done
1       1332  Done
2       1333  Done
3       1375  Done
4       1376  Done
...      ...   ...
3805    9993   NaN
3806    9994   NaN
3807    9995   NaN
3808    9996   NaN
3809    9997   NaN

[3810 rows x 2 columns]

In [8]:
id_company = 1301
file_name = '2022_Q3_決算短信(2023_2_3).pdf'
path_save = 'tests/'
text = convert_pdf_to_text(path_save + f'Data/{id_company}/PDF/{file_name}')
ocr_pdf(path_save + f'Data/{id_company}/PDF/{file_name}')
text_ = convert_pdf_to_text('tests/ocr.pdf')

[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
The output file size is 8.84× larger than the input file.
Possible reasons for this include:
--force-ocr was issued, causing transcoding.
Optimization was disabled.

In [9]:
text = text_.replace(" ", "")
text

'2023年3月期第3四半期決算短信日本基準」BR)\n上場会社名株式会社極洋\nコード番号1301URLhttos;//www.kyokuyo.co.p\n代表者役職名)代表取締役社長氏名)井上ih\n問合せ先責任者役職名)常務取締役経営管理部長氏名)槽垣仁志\n四半期報告書提出予定日\n配当支払開始予定日2023年2月7日\n四半期決算補足説明資料作成の有無無\n四半期決算説明会開催の有無無\n1.2023年3月期第3四半期の連結業績%022年4月1日-2022年12月31日)\n)連結経営成績Rat)上場取引所2023年2月3日\n東\nTEL03-9545-0703\n自万円未満切捨て)\n⑯表示は、対前年同四半期増減率)\nーーレヒanhale親会社株主に帰属する\n百万円%百万円%百万円%百万円%\n2023年3月期第3四半期213.36/6.48,12442.28,33938.35964494\n2022年3月期第3四半期200.4//3.1571555.26,0305183,99123.9\n往)包括利益2023年3月期第3四半期5852百万円979%)2022年3月期第3四半期2956百万円ムA53.99%)\nww潜在株式調整後styし中#\nVRS1Pei1株当たり半期純利益円銭円銭\n2023年3月期第3四半期5558/ーー\n2022年3月期第3四半期3/1.07ーー\n2)連結財政状態\n総資産fiSE自己資本比率\n百万円百万円%\n2023年3月期第3四半期166,09546,90228.6\n2022年3月期130,46042,17432.1\n参考)自己資本2023年3月期第3四半期47.466百万円2022年3月期42.705百万円\n2.配当の状況\n年間配当金\n第1四半期末第2四半期末第3四半期末期末合計円銭円銭円銭円銭円銭\n2022年3月期ーーーーーー90.0090.00\n2023年3月期ーーーーーー\n2023年3月期7)90.0090.00\n往)直近に公表されている配当予想からの修正の有無:無\n3.2023年3月期の連結業績予想202244月1日-202343月31日)\n⑯表示は、対前期増減率)\nーーレヒanhale親会社株主に帰属する|1株当たりvit=|HE|\nalia=RAStieFs当期純利益当期純利益百万円%BAA%BAA%BAA%円銚\n通期215,0008.47,000957,0001.449005]45549\n往)直近に公表されている業績予想からの修正の有無:無\n※注記事項\n1)当四半期連結果計期間における重要な子会社の異動連結範囲の変更を伴う特定子会社の異動)\n新規1社#t%)KyokuyoVinaFoodsCo.Ltd.、除外一社杜名)\nQ)四半期連結財務諸表の作成に特有の会計処理の適用:無\n6)会計方針の変更会計上の見積りの変更修正再表示\n会計基準等の改正に伴う会計方針の変更\n②①以外の会計方針の変更\nee会計上の見積りの変更\n④修正再表示\n@)発行済株式数普通株式):有\n①期末発行済株式数自己株式を含む)2023年3月期3010.928.283株|2022年3月期10.928.283株\n②期末自己株式数2023年3月期30211,639株|2022年3月期170.523株\n③期中平均株式数四半期累計)2023年3月期3010,729,529株|2022年3月期3Q10.757.726株\n注)当社は業績連動型株式報酬制度を導入しており、期末自己株式数には当該信託口が保有する当社株式が含まれております。また、当該信託口が保\n有する当社株式を、期中平均株式数の計算において控除する自己株式に含めております。\n※四半期決算短信は公認会計士又は監査法人の四半期レビューの対象外です\n※業績予想の適切な利用に関する説明、その他特記事項\n本資料に記載されている業績見通し等の将来に関する記述は、当社が現在入手している情報及び合理的であると判断する一定の前提に基づいており、その\n達成を当社として約束する趣旨のものではありません。また、実際の業績等は様々な要因により大きく<異なる可能性があります。業績予想の前提となる条件及\nび業績予想のご利用にあたっての注意事項等については、添付資料3ページON.当四半期決算に関する定性的情報⑧連結業績予想などの将来予測情\n報に関する説明」をご覧ください。\n株式会社極洋(G301)2023年3月期第8下半期決算短信\nOURSEEBLOBk\n1.‘4uA期決算にFETEPERcenceeeaepe\netCOREERCESaniUUeraOASecBodEERESEEESESTOSTOSTOSTOOTOSIOSIOSSpg\n2.BUNSHeinne&OEreeseP4\nSHIジラ5琴RFPP4\nC2)角半期連結損益及び包括利益計算書ーードドにPG\n(3)囲半期連結財務語表に関する注吉事項ーードードドにににPS\n(継続生業ブッBritAene関する注記)aaP8\n(株aaBRO1PBAaeLL1い変動があった坦谷の注記)すすすすササすすですすすすすすすませすすすすすすをすすすすPS\n(セグメント情報等)aaaP9\n株式会社極洋30D2023年3月期第38四半期決算短信\n1.3四半期決算に関する定性的情報\nCy(ESBOSCRTZBPH\n当第3ASHESTHCBUSbBaa,PsAEOBEX中でも、\n重利RESごインバウンドの生還性人なとに-より綴済活動の持ち直しがみみられ:ました。\n“asロンジンデ・ウクライナ間題の長期作や、急激な円安進行から円高に振れんるなど、修頑として先行\nA355BA7phhorex=ーー\n”AGEEa・食品業界におきましては、女oaGRCRESOPBRGivinAC,AEECIRA\nBOLERNN物流費のAlibi“JlkG,BeLVRARIREEOSRESELe.\nこのような状況の中で、中期経営計画『BuiidUpPlatform2024』(2021年度一2023年度)oer\nとして、PRSAROILeRO[SSRREOeanと持続的成長への挑戦」\nRELpBieBRSHED,kee®CHECTLENEATOSMMBeelLTEG,WiTERE\nHeer&(BRERAOR|を目Meh,|husdekyt)».BBSERICRYarcs»aeTmさき\nSS当第は関半期連結水計期間における当社グルー-mite,133徹87百万円(CaneialBel6.4%\n)、営業科益は81億24百万円(942)、経常和Hah人y9可(Mr\n)、親会社株主に帰属する四半期純利益は59億64百万円(前年周期比49.496となりました。\nグメント別の業績は次のとおりです。\nvineiEaea\n3022年前半からの相場上昇を受けて、第3DkPEOURLELI,AOR\nある年末商戦に-おいても、主要急種であるサケ、エビ、カニの取扱いは前年割れとなりました。IEE\nSth.FARISに向けて円高が進んだことで相場が急落し、計画を大幅に下回りました。一方で、海外事美\nについては、海外マーケットで競潮カがあるホタテやマグロの売上が仲長しました。この結果、売上・\n利益とも前年同期を下回りました。\n水産商事モグメントの売上高は983俺58百万円(前年同期此0.6%減)、営業利益33億4百万円(前年\n同期北29.3%減)となりました。\n(②食品モグメント\n業務用次凍食品は、量販店の稀菜売り場が好調を維持し、水産フライ・天ぶら類やエビフリッターな\nどの販売が拡大したほか、外食・観光産業の回復も進み、殆司種の売-osEMRESL|BTA4Roc\n(HeLELi:UNACIS,EBURBVeCORRS.EeLELIM,aAhEMIS\n十分に摘うことはできませんでした。\n市販用冷凍食品は、煮急・焼急を中心にコンビニエンスストア、宅配、ドラッグストアプ向けの販売\nBILEieoeees*価格改定が進行する中で、健康志向を捉えたサバ向等の新聞品が\n全体として取売は伸長しました。しかしながら、製造コスト上昇に北目めがかからず、収支面\nCHLIUMRINESSLE,Boku»Belaeoduaneと商品の投入により持ち直\nLeeOeeeeenetheneLau.するまでには至らず、原材#MM\nが収益を圧迫しました。この結果、売上は前年同期を上回りましたが、利益は前年同期を下回9まし\n品セモグメントの売上高は824億9吾方円(前年周期比員.3%増)|RRABARSSA(前年同期北15.396減)となりました。\nや\nteeC.HASYEBeTRGZSBeh,ii"のの、クロッマグ\nとに加え、回転寿司ルートドト向けを中心に加王品\nが好講に推移し、smeAMCERISHEHLELさらに、由玉クローグコロ癌本質の\n維持に努めることで収益を確保しました。海外まき網事業向の燃料費が増加しているものの、市場\n全体として水揚げが滅少したことによる引き谷いの高まりから、カツオの急条が上昇し、収支が政善しvosHILO7に起因する相場の高値#\n株式会社極洋(1301)2023年3月期第3四半期決算短\nました。この結果、売上・利益とも前年同期を上回りました。\nMeyAYPOREASIST(前年.8%増)、1営業利益は46億46百万円(Al\n年悦期比558.0増)となりました。\n④物流サービスセグメント\n‘aASE,SERRARIBASFELIXLRLIM,EATAERAOIRO\nBOOT.WAREHIELELic,PAR,HMRIEOMSDIRKL.FELISL\nた。この結果、売上は前年同期を上回りまましたが、利益は前年局期を下回りました。\n物流サービスセモダメントの売上高は0億21百万円(前年周期比16.5%増)、営楽利益はLiSSGHBE\n(前年周期比13.5%減)となりました。\ni\n(2)財政状態に関する説明\n当第3四半期連結会計期間末の総資産は、前連結会詩年度示に比べ356億38百万円増加し、1,660億95\nBAYとなり4csした。\n流動資産は、受取手形及び売失金や棚卸資産が増加したことなどにより、前連結会計年度未に比べ\nSRTRFRA.1SORTERTYBU,ERAS有形固定資産が増加したことなどICEY,EleHESSerEEFRACに比べ8)借68再万円増加|し、318億}百万円となりました\nQIRSHEL,SHIRSIA-S-OMUERBISMENLi->LPePick).sibereabeeneancie\n3007ral円eAし、1.191億93百万円となり手!した、\n純資産は、前連結会計年度未に比べ47億28百万円増加し、469簡2百万円となりました。\nとこの結果、自選資本比率は28.6%【バ前連結会計年度末比4.1ポイント減)となりました。\nSTE,\nSAPABZe&測情報に関する説明\n二子想に関しては、2022年5月13日に公表した業績予想から修正は行っておりません。\n株式会社極洋(1301)2023463月期第3四半期決算短信\n2.四半期連結財務諸表及び主な注記\n(1)四半期連結貸借対賠表\n(単位:AAD)\n前連結会計年度当第3四半期連結会計期間\n(2022年3月31日)(2022年12月31日)\n流動資産\n受取手形及び売持金28,68349,394\nその他9,6788,341\n流動資産合計99,527134,294\n有形固定資産18,89719,337\n投資その他の資産\n繰延税金資産1,1361,451\n貸倒引当金A,597人1,597\n固定資産合計30,93231,801\n株式会社極洋(1301)2023年3月期第3四半期決算短信\n(単位:百万円)\n前連結会計年度当第3四半期連結会計期間\n(2022年3月31日)(2022年12月31日)\n短期借入金15,71446,240\n示払法人税等1,0811,851\n未払金7,7915,800\nその他6,3447,249iy\nFh\nih\nmt\n引当金404400YS\ni\nPSN\nbitot\nRS\nトう\nie)\na\n合計31,34830,372HH\nFity4\nnFU\nTi\n純資産の部\n資本金5,6645,664\nBRA880,80利益剰余金32,50737,498\nBRペ\'e-株主資本合計39,07243,918\n©EONARIRAその他有価証券評価差額金3,2343,134\n292743ax\nnaa\n=a\nec\nFie\n=\nFt\nEDADAEAfatSAvitanpallttt\n+3,6323,0481コさ\n純資産合計42,17416,08\n(2)OSIMHEaO°LHSE\n第3DUSTSeTOTTe]株式会社極洋(1301)2023463月期第3四半期決算短信\n(単位:百万円)\n前第3四半期連結果計期間当第3四半期連結果計期間\n(自2021年4月1日(自2022年4月1日\n至2021年12月31日)至2022年12月31日)\n販売費及び一般管理費\n受取利候\n受取配当金\n持分法による投資利益\n受取保険金\n為替差益\n補助金収入\nその他\n営業外収益合計\n営業外費用\n支払利息\n訴訟損失引当3金繰入額\n貸倒引当金繰入額\nその他\n営業外費用合計\n経常利益\n特別利益\n固定資産処分益\n受取保険金\n国庫補助金等収入\n特別利益合計\n特別損失\n固定資産処分損\n減損損失\n災害による損失\n退職給付費用\n固定資産圧縮損\n投資有価証券評価損\n特別損失合計\n税金等調整前四半期純利益\n法人税、住民税及び事業税\n法人税等調整額\n法人税等合計\n四半期純利益\n(内訳)\n親会社株主に帰属する四半期純利益\n非支配株主に帰属する四半期純損失(へ)200,477213,387\n178,278188,010\n22,19920,aif\n16,48417,252\n0,7158,124\n10\n127139\n139J\n99183\n214144\n15877\n128160\n704758\n288356\n77\nA2一\n96179\n389044\n6,0308,339\n3307\n一45\n39一\n39352\n24\n1928\n一41\n157一\n33一\n7ーー\n22074\n5,8498,617\n1,6552,761\n239人ハ75\n1,8952,686\n3,9549,931\n3,9915,964\nA37A32\n株式会社極洋(1301)2023463月期第3四半期決算短信\n(単位:百万円)\n前第3四半期連結果計期間当第3四半期連結果計期間\n(自2021年4月1日(自2022年4月1日\n至2021年12月31日)至2022年12月31日)\nその他有価証券評価差額金人1,079人へ99\nその他の包括利益合計A997人へ79\n(内訳)\n非支配株主に係る四半期包括利益人へ114A27\nとoe)\nwe“4Speeとあり了feB0前提に関\nFAR\nTEERAU,株式会社\neeすず"©owe事項\n8極洋(G301D2ド3月期第8現半期決\n(セグメント情報等)株式会社極洋(1301)2023年3月期第3四半期決算短信\n1前第3四半期連結果計期間(自2021年4月1日至2021年12月31日)\n1.報告セグメントごとの売上高及び利益又は損失の金額に関する情報\n(単位:百万円)\n四半期連結\n流-調整額|,赴益及び水産商事|食品|mae|P|その他|合計|AEE|caipacat算書計上額\n(注2)\n売上高\n外部顧客への売上高98,95174,01326,334876301]200,477ー200,477\nセグメント間の内部[本またモエ22,6254,6513,2968211,04232,43732,437一売上高又は振答高“\n計121,57778,66529,6301,6981,344]232,915}A332,437200,477\nセグメント利益4,675951706180856,599A8839,715\nGE)1.\nております。全社費用は、主に親会社本社の総務部門等管理部門に係る費用であります。\n2.セグメント利益は、四半期連結損益及び包括利益計算書の営業利益と調整を行っております。\n2.報告セグメントごとの固定資産の減損損失又はのれん等に関する情報\n重要性が乏しいため、記載を省略しております。\n当第3四半期連結累計期間(自2022年4月1日至202247124318)\n1.報告セグのメントごとの売上高及び利益又は損失の金額に関する情報セグメント利益の調整額883百万円には、各報告セグメントに配分していない全社費用935百万円が含まれ\n(単位:百万円)\n四半期連結yas_SFike2aFEmtび\n水産商事|食品|mae|PM|その他|eat|AEE|caipvavaca算書計上額\n(注2)\n売上高\n外部顧客への売上高98,35882,40931,2731,021326]2138,387ー213,387\nセグメント間の内部_aeESMISHRRS28,0746,O715,9248661,07342,012}A42,012\nat126,43288,48037,1971,8881,400]255,399}A42,012213,387\nセグメント利益3,3048054,6461561439,056A9318,124\nGE)1.\nれております。全社費用は、主に親会社本社の総務部門等管理部門に係る費用であります。\n2.セグメント利益は、四半期連結損益及び包括利益計算書の営業利益と調整を行っております。\n2.報告セグメントごとの固定資産の減損損失又はのれん等に関する情報\n重要性が乏しいため、記載を省略しております。セグメント利益の調整額931百万円には、各報告セグメントに配分していない全社費用1,021百万円が含ま\n'

In [3]:
text[text.find('四半期報告書提出予定日') + 11] == '\n'

NameError: name 'text' is not defined

In [2]:
df = get_dividend(1332, 'tests/', True, False)
df

page has no images - all vector content will be rasterized at 400 DPI, losing some resolution and likely increasing file size. Use --oversample to adjust the DPI.
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
The output file size is 3.14× larger than the input file.
Possible reasons for this include:
--force-ocr was issued, causing transcoding.
Optimization was disabled.

page has no images - all vector content will be rasterized at 400 DPI, losing some resolution and likely increasing file size. Use --oversample to adjust the DPI.
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
The output file size is 1.39× larger than the input file.
Possible reasons for this include:
--force-ocr was issued, causing transcoding.
Optimization was disabled.

[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
The output file size is 8.05× larger than the input file.
Possible reasons for this include:
--force-ocr was issued, causing transcoding.
Optimization was disabled.

page has no images - all vector content will be rasterized at 400 DPI, losing some resolution and likely increasing file size. Use --oversample to adjust the DPI.
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
The output file size is 1.44× larger than the input file.
Possible reasons for this include:
--force-ocr was issued, causing transcoding.
Optimization was disabled.

page has no images - all vector content will be rasterized at 400 DPI, losing some resolution and likely increasing file size. Use --oversample to adjust the DPI.
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
The output file size is 3.30× larger than the input file.
Possible reasons for this include:
--force-ocr was issued, causing transcoding.
Optimization was disabled.

page has no images - all vector content will be rasterized at 400 DPI, losing some resolution and likely increasing file size. Use --oversample to adjust the DPI.
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
The output file size is 3.30× larger than the input file.
Possible reasons for this include:
--force-ocr was issued, causing transcoding.
Optimization was disabled.

[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
The output file size is 2.18× larger than the input file.
Possible reasons for this include:
--force-ocr was issued, causing transcoding.
Optimization was disabled.

page has no images - all vector content will be rasterized at 400 DPI, losing some resolution and likely increasing file size. Use --oversample to adjust the DPI.
[tesseract] lots of diacritics - possibly poor OCR
The output file size is 2.61× larger than the input file.
Possible reasons for this include:
--force-ocr was issued, causing transcoding.
Optimization was disabled.

page has no images - all vector content will be rasterized at 400 DPI, losing some resolution and likely increasing file size. Use --oversample to adjust the DPI.
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
The output file size is 5.90× larger than the input file.
Possible reasons for this include:
--force-ocr was issued, causing transcoding.
Optimization was disabled.

       time      time2
0   2022_Q1
1   2021_Q1
2   2020_Q1
3   2019_Q1
4   2018_Q1
5   2017_Q1          B
6   2016_Q1          B
7   2015_Q1
8   2014_Q1
9   2013_Q1
10  2012_Q1
11  2011_Q1
12  2010_Q1
13  2009_Q1
14  2008_Q1
15  2022_Q2  5_12_2022
16  2021_Q2  6_12_2021
17  2020_Q2  7_12_2020
18  2019_Q2  2_12_2019
19  2018_Q2  3_12_2018
20  2017_Q2  4_12_2017
21  2016_Q2  5_12_2016
22  2015_Q2  7_12_2015
23  2014_Q2
24  2013_Q2
25  2012_Q2
26  2011_Q2  5_12_2011
27  2010_Q2  6_12_2010
28  2009_Q2  7_12_2009
29  2008_Q2  8_12_2008
30  2022_Q3
31  2021_Q3
32  2020_Q3
33  2019_Q3
34  2018_Q3
35  2017_Q3
36  2016_Q3
37  2015_Q3
38  2014_Q3
39  2013_Q3
40  2012_Q3
41  2011_Q3
42  2010_Q3
43  2009_Q3
44  2008_Q3
45  2022_Q4  12_6_2023
46  2021_Q4   6_6_2022
47  2020_Q4   7_6_2021
48  2019_Q4   8_6_2020
49  2018_Q4  10_6_2019
50  2017_Q4  11_6_2018
51  2016_Q4  12_6_2017
52  2015_Q4  13_6_2016
53  2014_Q4   9_6_2015
54  2013_Q4
55  2012_Q4
56  2011_Q4  11_6_2012
57  2010_Q4  10_6_2011
58  2009_Q4   9_6_2010
59  2008_Q4   9_6_2009

In [3]:
df

       time      time2
0   2022_Q1
1   2021_Q1
2   2020_Q1
3   2019_Q1
4   2018_Q1
5   2017_Q1
6   2016_Q1
7   2015_Q1
8   2014_Q1
9   2013_Q1        N/A
10  2022_Q2
11  2021_Q2
12  2020_Q2
13  2019_Q2
14  2018_Q2
15  2017_Q2
16  2016_Q2
17  2015_Q2
18  2014_Q2
19  2013_Q2        N/A
20  2022_Q3
21  2021_Q3
22  2020_Q3
23  2019_Q3
24  2018_Q3
25  2017_Q3
26  2016_Q3
27  2015_Q3
28  2014_Q3
29  2013_Q3        N/A
30  2022_Q4  28_6_2023
31  2021_Q4  29_6_2022
32  2020_Q4  25_6_2021
33  2019_Q4  26_6_2020
34  2018_Q4  27_6_2019
35  2017_Q4  28_6_2018
36  2016_Q4  29_6_2017
37  2015_Q4  29_6_2016
38  2014_Q4  26_6_2015
39  2013_Q4        N/A

In [3]:
ocr_pdf('tests/Data/1332/PDF/2017_Q2_決算短信(2017_11_2).pdf')
text_ = convert_pdf_to_text('tests/ocr.pdf')

page has no images - all vector content will be rasterized at 400 DPI, losing some resolution and likely increasing file size. Use --oversample to adjust the DPI.
[tesseract] lots of diacritics - possibly poor OCR
[tesseract] lots of diacritics - possibly poor OCR
The output file size is 1.44× larger than the input file.
Possible reasons for this include:
--force-ocr was issued, causing transcoding.
Optimization was disabled.

In [12]:
text_ = text_.replace(' ', '')
# text_
idx = text_.find('TEL')#配当支払開始予定日
time_text = text_[idx + 16: + idx + 27]
if time_text[0: 2] =='平成' or time_text[0: 2] == '20':
    matches = re.findall(r'\d+', time_text)
    if len(matches) == 3 :
        if int(matches[0]) > 2000:
            print( [f'{int(matches[2])}_{int(matches[1])}_{int(matches[0])}'])
        else:
            print( [f'{int(matches[2])}_{int(matches[1])}_{int(matches[0]) + 1988 }'])
    print('   -  ')

['4_12_2017']
   -